# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<$GOROOT/src/mk.$GOARCH

TARG=compress/flate
GOFILES=\
	deflate.go\
	huffman_bit_writer.go\
	huffman_code.go\
	inflate.go\
	reverse_bits.go\
	token.go\
	util.go\

<$GOROOT/src/mk.pkg
