# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<$GOROOT/src/mk.$GOARCH

TARG=go/ast
GOFILES=\
	ast.go\
	scope.go\
	filter.go\
	walk.go\

<$GOROOT/src/mk.pkg
