# Copyright 2009 The Go Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<$GOROOT/src/mk.$GOARCH

TARG=debug/dwarf
GOFILES=\
	buf.go\
	const.go\
	entry.go\
	open.go\
	type.go\
	unit.go\

<$GOROOT/src/mk.pkg
