</$objtype/mkfile
LIB=cc.a$O\

HFILES=\
	cc.h\
	y.tab.h\

YFILES=\
	cc.y\

OFILES=\
	y.tab.$O\
	lex.$O\
	mac.$O\
	dcl.$O\
	acid.$O\
	pickle.$O\
	bits.$O\
	com.$O\
	scon.$O\
	funct.$O\
	sub.$O\
	com64.$O\
	dpchk.$O\
	omachcap.$O\

</sys/src/cmd/mklib

$LIB:	$LIBOBJ
	ar vu $LIB $OFILES
