# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<$GOROOT/src/mk.$GOARCH

TARG=big
GOFILES=\
	arith.go\
	nat.go\
	int.go\

OFILES=\
	arith_$GOARCH.$O\

<$GOROOT/src/mk.pkg
