# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<$GOROOT/src/mk.$GOARCH

TARG=syscall
GOFILES=\
	errstr.go\
	exec.go\
	syscall.go\
	syscall_$GOOS.go\
	syscall_$GOOS_$GOARCH.go\
	zerrors_$GOOS_$GOARCH.go\
	zsyscall_$GOOS_$GOARCH.go\
	zsysnum_$GOOS_$GOARCH.go\
	ztypes_$GOOS_$GOARCH.go\

OFILES=\
	asm_$GOOS_$GOARCH.$O\

<$GOROOT/src/mk.pkg
