</$objtype/mkfile
TARG=	8g

OFILES=\
	enam.$O\
	list.$O\
	galign.$O\
	gobj.$O\
	ggen.$O\
	gsubr.$O\
	cgen.$O\
	cgen64.$O\
	peep.$O\
	reg.$O\

HFILES=\
	../gc/go.h\
	../8l/8.out.h\
	gg.h\
	opt.h\

LIB=../gc/gc.a$O

BIN=/$objtype/bin
</sys/src/cmd/mkone

$LIB: $LIBOBJ
	cd ../cc
	mk install
	mk clean

bound.$O:	bound.h

enam.$O: ../8l/enam.c
	$CC $CFLAGS ../8l/enam.c

%.$O: ../cc/%.c
	$CC $CFLAGS ../cc/$stem.c
