# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<$GOROOT/src/mk.$GOARCH

TARG=container/vector
GOFILES=\
	intvector.go\
	stringvector.go\
	vector.go\

<$GOROOT/src/mk.pkg
