</$objtype/mkfile
TARG=8a

HFILES=\
	a.h\
	y.tab.h\
	../8l/8.out.h\

OFILES=\
	y.tab.$O\
	lex.$O\
	../8l/enam.$O\

YFILES=\
	a.y\

</sys/src/cmd/mkone

YFLAGS=-D1 -d
lex.$O:	../cc/macbody ../cc/lexbody

