# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

<../../mk.conf

TARG=\
	8ga\

HFILES=\
	a.h\
	y.tab.h\
	../8l/8.out.h\

CFILES=\
	y.tab.c\
	lex.c\
	../8l/enam.c\

OFILES = ${CFILES:%.c=%.$O}

YFILES=\
	a.y\

</sys/src/cmd/mkone
YFLAGS=-d -D0

$OFILES: $HFILES

lex.$O:	../cc/macbody ../cc/lexbody

<../../mk.inc

clean:V:
	rm -f *.[$OS] [$OS].out $TARG $CLEANFILES
